### ISSUE TITLE
Which is recommended: a large tool withany options or many smaller tools?

### ISSUE THREAD

**Issue by sudomain** [sigoden/llm-functions#100]
Hello,

If we're using the llm-functions repo and we want to maximize the quality of the response/minimize token usage, is it better to have many options for one large tool or many smaller tools for the agent to use? For example, I'm writing a tool called `create_flashcard.py` and can give it many options such as `--question` and `--answer`. alternatively, I can also write smaller tools such as `create_short_answer_card.py` which just calls `create_flashcard.py` with the correct options behind the scenes

**Comment by sigoden** [comment]
There is no answer, please try to find the answer yourself by coding and testing
