### ISSUE TITLE
realpath: illegal option -- m

### ISSUE THREAD

**Issue by eugeis** [sigoden/llm-functions#104]
**Describe the bug**
I am using the coder agent on Macbook and getting the error:

```
realpath: illegal option -- m
usage: realpath [-q] [path ...]

```

I checked and the command "realpath -m" is used in multiple tools.

In Mac the command realpath does not have -m parameter.
usage: realpath [-q] [path ...]

**Comment by sigoden** [comment]
The built-in Bash in macOS is version 3.2 (released in 2007), and the known tools (ls, cp, grep, sed, awk, etc.) are based on BSD. 
For better functionality and compatibility, it is recommended to install Bash version 5 and GNU tools.


Use `brew` to install Bash and GNU tools:

```sh
brew install bash coreutils gawk gnu-sed grep
```

And update the `PATH` environment variable:
```sh
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/gawk/libexec/gnubin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/grep/libexec/gnubin:$PATH"
```

**Comment by eugeis** [comment]
thx
