### ISSUE TITLE
Controls displaying the results from function call

### ISSUE THREAD

**Issue by sigoden** [sigoden/llm-functions#110]
For some function calls, displaying their results is indeed valuable. We use environment variables to control this.

`LLM_TOOL_DUMP_RESULT=1`: Dump results from all tools.
`LLM_TOOL_DUMP_RESULT_<TOOL_NAME>=1`: Dump result from the `TOOL_NAME` tool.
`LLM_AGENT_DUMP_RESULT_<AGENT_NAME>=1`: Dump results from all tools of the `AGENT_NAME` agent.
`LLM_AGENT_DUMP_RESULT_<AGENT_NAME>_<FN_NAME>=1`: Dump results from the `FN_NAME` tool of the `AGENT_NAME` agent.

**Comment by sigoden** [comment]
We are unlikely to support the silence function call log (dimmed text like `call <tool-name>/<agent-name:agent-action> <json-data>`) because they are too important.

After hiding the log, you won't even know whether the function calling was invoked or not.

To address the issue of the `<json-data>` text being too large, we could trim it and add an ellipsis.

**Comment by einarpersson** [comment]
Hehe ok. Just to explain my use case: I am actually experimenting with creating tools that are themselves specialized aichat roles (with a own set of tools). Cool huh? :) Would love to hear if you have tried anything similar. It was in that context that I wanted to limit the output as much as possible, as I wanted to hide "implementation details" from the calling aichat assistant as to save tokens. 

But I have also experienced the function call arguments being verbose when using the assistant directly myself, especially when it is doing write to file.

Being able to at least limit the json-data would be useful (...) . I understand that it is of principal importance to show function call invokations. But perhaps not all the arguments.

But I suppose this also has to be a toggle/setting/env var, as in other context you def want to see all arguments!

**Comment by sigoden** [comment]
Currently, we don't see a need to hide the call logs.

If stdout is not a tty, the call logs and result logs are hidden.

![image](https://github.com/user-attachments/assets/12ff505d-38b8-455e-93f3-bcdc80ef9d1e)
