### ISSUE TITLE
Docs: How use libraries in py/js-tools?

### ISSUE THREAD

**Issue by einarpersson** [sigoden/llm-functions#115]
**Problem:** I would like to use external libraries in python / javascript tools without having to install them in the global environment. External libraries are essential to making useful tools. But installing all these libs in global node or python env is a no-go for me.

Is this currently possible, if so, how? Consider adding a sample tool showing how it's done for python resp. nodejs.

If it is not possible, can you implement it? And can you conceive a workaround given how things are setup?

I guess one workaround would be to only use bash-scripts and let the bash scripts setup the right env and call any js/py code. But it would of course not be as nice as if it was supported out-of-the box. Since you recently added an env variable for controlling whether the result should be dumped to the user or not, perhaps a similar solution could be used here. Set an optional env variable that somehow points to the right environment for that tool. Or perhaps you have a better idea ( - or perhaps this is already solved).

Thanks!

**Comment by einarpersson** [comment]
I created a wrapper script for aichat that sources a common virtual environment for all my python tools.

**Comment by sigoden** [comment]
We are not going to maintain a package.json or requirements.txt. Users need to maintain it themselves.

But we will indeed offer some helper utilities to check the dependencies and print missing packages.

For Python, something similar to virtualenv is necessary. Since llm-functions supports dotenv, users can place Python-related environment variables in a `.env` file to ensure the Python path and libraries are set correctly.

**Comment by einarpersson** [comment]
Yes, I did not suggest that you would mainain the package.json or requirements.txt

I just wanted to get some hint on how / if you could still use external libs (or rather: specify which env to use for a certain tool). As i said in the following reply I did manage to get it working with a wrapper script that activates a virtual environment, so I am good for the moment.

_"llm-functions supports dotenv"_, that sounds great but i'm not quite sure what it means in practice. Perhaps add this to the doc with a simple example?

**Comment by sigoden** [comment]
@einarpersson You can try #116.
