### ISSUE TITLE
Cross-platform (I.E windows) compatibility?

### ISSUE THREAD

**Issue by lurebat** [sigoden/llm-functions#12]
This is pretty impressive all around, but using bash (plus all the other needed requirements) makes it work only on linux-based systems (seems to require cygwin on windows, which is a big dependency and doesn't perform well).

So while the project doesn't have too much code, it might be worth considering to make the main script depend on only one cross platform thing.

As far as I can see, its functionality is just building a json file from the folder structure, couldn't this just be folded in into aichat itself?

If not, can it maybe be written in a cross-platform language - python, node or even something like https://github.com/sagiegurari/duckscript

Not to mention, bash is full of traps and foot-guns, and maintaining it will get harder as it expands.

**Comment by sigoden** [comment]
LLM-Functions is cross-platofrm, Github CI can prove this.

On Windows, the only requirement is Git (which includes Bash, Cygwin and other GNU tools). Installing Git is no more troublesome than installing Node.js, Ruby, or Python.

We don't believe bash is full of traps and pitfalls, it is actually the most convenient and efficient way to write llm functions.

LLM-Functions support written functions in bash, python, node.js and ruby.  Users have the freedom to write functions in any language they prefer. We don't want any arguments about language.
