### ISSUE TITLE
Reusability of rags from an agent

### ISSUE THREAD

**Issue by oatmealm** [sigoden/llm-functions#126]
I'm a little bit confused about the reusability of rags. I can see that specifying a documents section in the agents definition creates a rag. I was not sure if the paths must be relative  to the agents own directory. Also, if I could re-use an existing rag I created manually and have it available to the agent.

**Comment by sigoden** [comment]
>  I was not sure if the paths must be relative to the agents own directory.

It is clear that the documents are related to the agent directory. see https://github.com/sigoden/llm-functions/tree/main/agents/demo#documents

>  Also, if I could re-use an existing rag I created manually and have it available to the agent.

No, you could not. The agent has only one RAG that is built from the documents in agent's index.yaml.
