### ISSUE TITLE
[Feature Request] CodeAct agent

### ISSUE THREAD

**Issue by refinism** [sigoden/llm-functions#127]
**Is your feature request related to a problem? Please describe.**
I want to implement a SOTA agent called CodeAct based on [OpenHands](https://github.com/All-Hands-AI/OpenHands).

**Describe the solution you'd like**
I want to implement the bash script version of the Agent. I want your opinion about "bash as model output", its risks and output quality.

**Describe alternatives you've considered**
Another way is to remove the dependencies of the python code from OpenHands and run it as python script. 

**Additional context**
CodeAct Implementation: https://github.com/All-Hands-AI/OpenHands/tree/a2779fe2f6c9ab29508676f21242b1c6b88e2f67/openhands/agenthub/codeact_agent

**Comment by sigoden** [comment]
1. llm-functions + aichat already  achieve the effect of CodeAct.
![image](https://github.com/user-attachments/assets/999dfeaa-16e9-4945-b832-cfdf76d2ac54)

2.  Agents in llm-functions like Openai GPTs,  needs to be given more specific tasks
