### ISSUE TITLE
Windows paths aren't handled correctly

### ISSUE THREAD

**Issue by lurebat** [sigoden/llm-functions#13]
```bash
aichat -r %functions% what time is it
Call get_current_time '{}'
Call get_current_time '{}':
    /bin/bash: C:UsersmeAppDataRoamingaichatfunctionsshget_current_time.sh: No such file or directory
```

It seems to try to run the file via the windows path, so the backslashes are replaced with nothing and the function doesn't work.

**Comment by sigoden** [comment]
@lurebat 

Did you setup accordingthe readme instructions?

Can you try running `argc call get_current_time '{}'`?

**Comment by lurebat** [comment]
Running the command directly does work, so it seems that it's aichat who gets it wrong.
Maybe it's related to the symlinking?


Setup I made:

I cloned the repo, made functions.txt with the following content:

```
get_current_time.sh
get_current_weather.sh
get_web_page.sh
search_duckduckgo.sh
search_wolframalpha.sh
may_execute_py_code.py
may_execute_js_code.js
```

ran `argc build` and then `argc install`

**Comment by sigoden** [comment]
aichat simply execute `./bin/get_current_time.cmd`,  that's all.

It seems the bash path is incorrect,  #15  fixed it.

please sync the repo, run `argc build`, and try again.

**Comment by lurebat** [comment]
Confirmed working
