### ISSUE TITLE
fs_write should have a confirmation prompt

### ISSUE THREAD

**Issue by FitzWM** [sigoden/llm-functions#137]
**Is your feature request related to a problem? Please describe.**

I was messing around with the various tools today, getting a feel for them, and I had the fs functions, web_search, and execute_command enabled. I did a few searches, then asked Claude what the current best settings for MPV were for 4K/HDR content. Rather than searching and reporting, as it had before, Claude instead found some settings and then proceeded to wipe out my existing MPV configuration file. No warning, no confirmation - and I didn't even tell it do anything, only to tell me what the best settings were.

It's partially my fault for not having it backed up, as well as for trusting a new program - although I'd argue I more trusted it not to invoke the function without my asking it to - but I still spent a couple hours today rewriting my config file.

**Describe the solution you'd like**

fs_write should ask for confirmation on what it's about to do, similar to execute_command.

**Describe alternatives you've considered**

At the very least, it should have a means to detect an existing file and copy it to file.txt.bak or something. If that's too cumbersome for scripting, etc., then maybe split the functionality into two functions: one that requires confirmation and one that doesn't.

**Additional context**

**Comment by sigoden** [comment]
`fs_write` uses the current directory as a safe directory; only non-safe directories will require confirmation.

![image](https://github.com/user-attachments/assets/f22a1a13-5134-46f4-8b2e-48e67d386b34)

`fs_write` is used to create a new file, whereas `fs_patch` is used to modify an existing file. It can generate a diff and requires confirmation.

**Comment by sigoden** [comment]
I thought for a moment that if we are going to overwrite an existing file then it would make sense to ask for confirmation.

I will implement this feature.
