### ISSUE TITLE
`argc install` returns `ln: : No such file or directory`

### ISSUE THREAD

**Issue by jacksongoode** [sigoden/llm-functions#3]
Install tutorial doesn't appear to work on latest aichat 0.17.0 with latest llm-functions on macOS.

**Comment by sigoden** [comment]
```
ln -s "$(pwd)" "$(aichat --info | grep functions_dir | awk '{print $2}')"
# OR
argc install
```
Does macOS not have the `ln` command?

**Comment by sigoden** [comment]
This is because aichat v0.17.0 does not support function calling. You will need to build from source or wait for v0.18.0.
