### ISSUE TITLE
Mix of existent and nonexistent files in README instructions is confusing

### ISSUE THREAD

**Issue by ngirard** [sigoden/llm-functions#46]
README.md contains

> - Create a `./agents.txt` file with each agent name on a new line.
> 
> ```
> todo-sh
> hackernews
> ```

which I found confusing, because `todo-sh` exists within the repo, but `hackernews` doesn't.

Cheers, and thanks so much for your work !

**Comment by sigoden** [comment]
This is not a problem. Users should be careful when copying and pasting.

>  I was going to add Hacker News, I just haven't gotten around to it yet.
