### ISSUE TITLE
LLM_AGENT_CACHE_DIR not documented nor default fallback

### ISSUE THREAD

**Issue by einarpersson** [sigoden/llm-functions#54]
**Describe the bug**

`LLM_AGENT_CACHE_DIR` is not documented [here](https://github.com/sigoden/aichat/wiki/Environment-Variables) and does not seem to have a default / fallback value.

**To Reproduce**

```
todo-sh>> add todo make a lasagne
Call todo-sh add_todo {"desc":"make a lasagne"}
No such file or directory (os error 2)
```

**Expected behavior**
I expected it to just work, since I am following the README [here](https://github.com/sigoden/llm-functions)

**Environment**
```
❯ aichat --version
aichat 0.19.0
```

**Additional context**

**Comment by sigoden** [comment]
The `LLM_AGENT_CACHE_DIR` is not provide by `aichat`. It comes from llm-function `run-agent.*`

https://github.com/sigoden/llm-functions/blob/970ed06d2b5759e8d17aeed55fbfde591fb0ff84/scripts/run-agent.sh#L33-L35

**Comment by sigoden** [comment]
If you want to test agent, please try the argc command:
```
argc run@agent todo-sh 
```

https://github.com/sigoden/llm-functions/assets/4012553/7019835e-7f7b-4775-8d7c-bb03b9a259b9
